spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: c4fcc1e62645c7534822
            clientSecret: 19d994c0356412b29303d9ae8d1a9f0e3dd3204f
          google:
            client-id: 218347835808-ecfnjslvj3uf7nhltciibejqg9hel45c.apps.googleusercontent.com
            client-secret: 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
          kakao:
            client-id: dffc9bf69064496b00bb141fb605536b
            client-secret: x8NkJkIZxHhhRVEcbRsDc2neyq8zijZR
            redirect-uri: http://localhost:8080/oauth2/authorization/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: 
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
