server:
  port: 8080

spring:
  # profiles:
  #   include:
  #   - oauth
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:~/test
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug